extends: theme-check:recommended

RequiredLayoutThemeObject:
  enabled: true

ImgLazyLoading:
  enabled: true

AssetSizeCSS:
  enabled: true
  threshold_in_bytes: 100000

AssetSizeJavaScript:
  enabled: true
  threshold_in_bytes: 100000

UnusedAssign:
  enabled: true

DeprecatedFilter:
  enabled: true
